version: '2.4'

services:

  dv_mkt_postgres:
    container_name: "dv_mkt_postgres"
    hostname: mkt_postgres
    image: postgres:${POSTGRES_VERSION}
    restart: on-failure
    environment:
      - POSTGRES_DB=dv_mkt_pg
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - ./docker-dev-volumes/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    network:
      - dv-hub-network
      
networks:
  dv-hub-network:
    driver: bridge